# Generated by Django 3.2.4 on 2021-06-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20210627_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
